# Generated by Django 6.0.8 on 2026-08-04 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Bairro')),
                ('latitude', models.FloatField(default=9.4137, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=40.5036, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data/Hora da Ocorrência')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Pendente'), ('RESOLVIDO', 'Resolvido')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencias.bairro', verbose_name='Bairro')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_hora'],
            },
        ),
    ]
