# Generated by Django 6.0.8 on 2026-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='bairro',
            name='latitude',
            field=models.FloatField(default=-9.4137, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='longitude',
            field=models.FloatField(default=-40.5036, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status'),
        ),
    ]
